# Generated by Django 3.2.5 on 2021-07-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название кафе')),
                ('adress', models.CharField(max_length=255, verbose_name='адресс кафе')),
            ],
        ),
        migrations.CreateModel(
            name='flowershop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название магазина')),
                ('adress', models.CharField(max_length=255, verbose_name='адресс кафе')),
            ],
        ),
        migrations.CreateModel(
            name='park',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название парка')),
                ('adress', models.CharField(max_length=255, verbose_name='Адрес парка')),
            ],
        ),
    ]
