# Generated by Django 3.2.5 on 2021-07-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210714_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='advices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='aquapark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название аквапарка')),
                ('adress', models.CharField(max_length=255, verbose_name='адрес аквапарка')),
            ],
        ),
    ]
