# Generated by Django 3.2.5 on 2021-07-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_advices_aquapark'),
    ]

    operations = [
        migrations.CreateModel(
            name='cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название кинотеатра')),
                ('adress', models.CharField(max_length=255, verbose_name='адрес кинотеатра')),
            ],
        ),
        migrations.AlterField(
            model_name='park',
            name='adress',
            field=models.CharField(max_length=255, verbose_name='адрес парка'),
        ),
    ]
