# Generated by Django 3.2.5 on 2021-07-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_cinema_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название кинотеатра')),
                ('adress', models.CharField(max_length=255, verbose_name='адрес кинотеатра')),
                ('station', models.CharField(default='', max_length=255, verbose_name='стацния')),
            ],
        ),
    ]
