# Generated by Django 3.2.5 on 2021-07-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_theater'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquapark',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cinema',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
