# Generated by Django 3.2.5 on 2021-07-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_user_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
