# Generated by Django 3.2.5 on 2021-07-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_theater_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theater',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
