# Generated by Django 3.2.5 on 2021-08-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_alter_theater_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
