# Generated by Django 3.2.5 on 2021-08-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20210818_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquapark',
            name='allrate',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='allrate',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cinema',
            name='allrate',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='allrate',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
