# Generated by Django 3.2.5 on 2021-08-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20210818_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquapark',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='delicious',
            field=models.CharField(default='', max_length=255, verbose_name='Предпочтения'),
        ),
    ]
