# Generated by Django 3.2.6 on 2021-09-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_auto_20210913_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushkin_card',
            name='category',
            field=models.CharField(default='', max_length=255),
        ),
    ]
